version: '3'

services:

  redis:
    image: redis:alpine
    container_name: redis

  web:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./web:/web

  celery:
    restart: always
    build:
      context: .
    command: celery -A hrvscihub worker -l INFO
    volumes:
      - ./web:/web
    container_name: celery
